name: s3 - Output Information
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context
        run: echo $JSON
        env:
          JSON: ${{ toJSON(github)}}
          #https://github.com/actions/runner/issues/1656
